# Generated by Django 4.2.1 on 2023-07-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_pin_code_order_post_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
